plugins:
  ./packages/link-adjacent/lib/index.mjs: {}
  ./packages/order-esm-import/lib/index.mjs:
    fix: true
  ./packages/prettier/lib/index.mjs:
    prettier-options: .prettierrc.yml
  ./packages/eslint/lib/index.mjs:
    babel-parser-options:
      sourceType: module
  ./packages/c8/lib/index.mjs: {}
