plugins:
  '@bercow/link-adjacent': {}
  '@bercow/order-esm-import':
    fix: true
  '@bercow/prettier':
    prettier-options: .prettierrc.yml
  '@bercow/eslint':
    babel-parser-options:
      sourceType: module
  '@bercow/c8': {}
