root: true
extends:
  - eslint:recommended
env:
  es6: true
  node: true
rules:
  no-console:
    - warn
  no-unused-vars:
    - error
    - args: none
parserOptions:
  ecmaVersion: 2020
  sourceType: module
