root: true
extends:
  - eslint:recommended
env:
  es6: true
  node: true
rules:
  no-console:
    - warn
  no-unused-vars:
    - error
    - vars: all
      varsIgnorePattern: "^_"
      args: all
      argsIgnorePattern: "^_"
      caughtErrors: all
      caughtErrorsIgnorePattern: "^_"
      ignoreRestSiblings: false
parserOptions:
  ecmaVersion: 2022
  sourceType: module
